namespace Spot.Build;

/// <summary>
/// The static <c>wwwroot</c> assets for a browser build: the host page and the JavaScript that bridges the
/// engine's <c>[JSImport]</c>/<c>[JSExport]</c> surface to the DOM. <c>main.js</c> owns the canvas' WebGL2
/// context and implements the <c>spot-gl</c> (graphics) and <c>spot-host</c> (fetch) module imports that
/// <see cref="Spot.Rendering.IGraphicsDevice"/>'s WebGL2 backend and the browser host call into, then drives
/// the frame loop through <c>requestAnimationFrame</c> and forwards DOM input events.
/// </summary>
internal static class BrowserTemplate
{
    /// <summary>Builds the host page for a browser build with the given window title.</summary>
    public static string IndexHtml(string title) => """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>__TITLE__</title>
    <style>
        html, body { margin: 0; height: 100%; background: #0b0b12; overflow: hidden; }
        #canvas { display: block; width: 100vw; height: 100vh; touch-action: none; }
    </style>
</head>
<body>
    <canvas id="canvas" tabindex="0"></canvas>
    <script type="module" src="./main.js"></script>
</body>
</html>
""".Replace("__TITLE__", title);

    /// <summary>
    /// Builds <c>main.js</c> for a browser build. The cooked content is served under <c>content/</c> with a
    /// <c>content-index.txt</c> manifest of files to preload; <paramref name="startScene"/> is the cooked start
    /// scene reference passed to the engine host.
    /// </summary>
    public static string MainJs(string startScene) => """
// Generated by Spot.Build. Bridges the DOM + WebGL2 to the Spot engine's browser host.
import { dotnet } from './_framework/dotnet.js';

const ENGINE_ASSEMBLY = 'Spot.Engine';
const CONTENT_BASE = 'content';
const MANIFEST_PATH = 'manifest.json';
const START_SCENE = '__START_SCENE__';

const canvas = document.getElementById('canvas');

function sizeCanvas() {
    const dpr = window.devicePixelRatio || 1;
    canvas.width = Math.max(1, Math.floor(canvas.clientWidth * dpr));
    canvas.height = Math.max(1, Math.floor(canvas.clientHeight * dpr));
    return [canvas.width, canvas.height];
}

const [initW, initH] = sizeCanvas();

const gl = canvas.getContext('webgl2', { antialias: true, alpha: false });
if (!gl) {
    document.body.insertAdjacentHTML('beforeend', '<p style="color:red">WebGL2 is not available in this browser.</p>');
    throw new Error('WebGL2 not supported');
}

// JS-side handle table: C# refers to GL objects (buffers, shaders, programs, textures, uniform locations)
// by integer index. Index 0 is reserved as the null handle.
const objs = [null];
const reg = (o) => { objs.push(o); return objs.length - 1; };

const glImports = {
    viewport: (x, y, w, h) => gl.viewport(x, y, w, h),
    scissor: (x, y, w, h) => gl.scissor(x, y, w, h),
    clearColor: (r, g, b, a) => gl.clearColor(r, g, b, a),
    clear: (mask) => gl.clear(mask),
    enable: (cap) => gl.enable(cap),
    disable: (cap) => gl.disable(cap),
    blendFunc: (s, d) => gl.blendFunc(s, d),
    drawArrays: (mode, first, count) => gl.drawArrays(mode, first, count),
    drawElements: (mode, count, type, offset) => gl.drawElements(mode, count, type, offset),

    createBuffer: () => reg(gl.createBuffer()),
    bindBuffer: (target, b) => gl.bindBuffer(target, objs[b]),
    bufferData: (target, data, usage) => gl.bufferData(target, data.slice(), usage),
    bufferDataSize: (target, size, usage) => gl.bufferData(target, size, usage),
    bufferSubData: (target, offset, data) => gl.bufferSubData(target, offset, data.slice()),
    deleteBuffer: (b) => gl.deleteBuffer(objs[b]),

    createVertexArray: () => reg(gl.createVertexArray()),
    bindVertexArray: (v) => gl.bindVertexArray(objs[v]),
    enableVertexAttribArray: (i) => gl.enableVertexAttribArray(i),
    vertexAttribPointer: (i, size, type, norm, stride, offset) =>
        gl.vertexAttribPointer(i, size, type, norm, stride, offset),
    deleteVertexArray: (v) => gl.deleteVertexArray(objs[v]),

    createShader: (type) => reg(gl.createShader(type)),
    shaderSource: (s, src) => gl.shaderSource(objs[s], src),
    compileShader: (s) => gl.compileShader(objs[s]),
    getShaderCompileStatus: (s) => gl.getShaderParameter(objs[s], gl.COMPILE_STATUS),
    getShaderInfoLog: (s) => gl.getShaderInfoLog(objs[s]) ?? '',
    deleteShader: (s) => gl.deleteShader(objs[s]),

    createProgram: () => reg(gl.createProgram()),
    attachShader: (p, s) => gl.attachShader(objs[p], objs[s]),
    detachShader: (p, s) => gl.detachShader(objs[p], objs[s]),
    linkProgram: (p) => gl.linkProgram(objs[p]),
    getProgramLinkStatus: (p) => gl.getProgramParameter(objs[p], gl.LINK_STATUS),
    getProgramInfoLog: (p) => gl.getProgramInfoLog(objs[p]) ?? '',
    deleteProgram: (p) => gl.deleteProgram(objs[p]),
    useProgram: (p) => gl.useProgram(objs[p]),

    getUniformLocation: (p, name) => { const l = gl.getUniformLocation(objs[p], name); return l ? reg(l) : -1; },
    uniform1i: (loc, v) => { if (loc >= 0) gl.uniform1i(objs[loc], v); },
    uniform1f: (loc, v) => { if (loc >= 0) gl.uniform1f(objs[loc], v); },
    uniform2f: (loc, x, y) => { if (loc >= 0) gl.uniform2f(objs[loc], x, y); },
    uniform3f: (loc, x, y, z) => { if (loc >= 0) gl.uniform3f(objs[loc], x, y, z); },
    uniform4f: (loc, x, y, z, w) => { if (loc >= 0) gl.uniform4f(objs[loc], x, y, z, w); },
    uniformMatrix4fv: (loc, data) => { if (loc >= 0) gl.uniformMatrix4fv(objs[loc], false, new Float32Array(data.slice().buffer)); },

    createTexture: () => reg(gl.createTexture()),
    bindTexture: (unit, tex) => { gl.activeTexture(gl.TEXTURE0 + unit); gl.bindTexture(gl.TEXTURE_2D, objs[tex]); },
    texParameteri: (name, value) => gl.texParameteri(gl.TEXTURE_2D, name, value),
    texImage2DRgba8: (w, h, data) =>
        gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA8, w, h, 0, gl.RGBA, gl.UNSIGNED_BYTE, data.slice()),
    generateMipmap2D: () => gl.generateMipmap(gl.TEXTURE_2D),
    deleteTexture: (t) => gl.deleteTexture(objs[t]),
};

const hostImports = {
    fetchText: async (url) => {
        const r = await fetch(url);
        if (!r.ok) throw new Error(`fetch ${url}: ${r.status}`);
        return await r.text();
    },
    fetchBase64: async (url) => {
        const r = await fetch(url);
        if (!r.ok) throw new Error(`fetch ${url}: ${r.status}`);
        const bytes = new Uint8Array(await r.arrayBuffer());
        let binary = '';
        const chunk = 0x8000;
        for (let i = 0; i < bytes.length; i += chunk) {
            binary += String.fromCharCode.apply(null, bytes.subarray(i, i + chunk));
        }
        return btoa(binary);
    },
};

const { setModuleImports, getAssemblyExports, getConfig, runMain } = await dotnet.create();
setModuleImports('spot-gl', { gl: glImports });
setModuleImports('spot-host', { host: hostImports });

getConfig();
const exports = await getAssemblyExports(ENGINE_ASSEMBLY);
const host = exports.Spot.Browser.BrowserHost;

await runMain();

// Forward DOM input to the engine host.
canvas.focus();
window.addEventListener('keydown', (e) => { host.KeyDown(e.code); if (e.key.length === 1) host.TextInput(e.key); e.preventDefault(); });
window.addEventListener('keyup', (e) => { host.KeyUp(e.code); e.preventDefault(); });
canvas.addEventListener('pointermove', (e) => host.PointerMove(e.offsetX * (window.devicePixelRatio || 1), e.offsetY * (window.devicePixelRatio || 1)));
canvas.addEventListener('pointerdown', (e) => { canvas.focus(); host.PointerDown(e.button); });
window.addEventListener('pointerup', (e) => host.PointerUp(e.button));
canvas.addEventListener('wheel', (e) => { host.Wheel(e.deltaX, e.deltaY); e.preventDefault(); }, { passive: false });
canvas.addEventListener('contextmenu', (e) => e.preventDefault());

window.addEventListener('resize', () => { const [w, h] = sizeCanvas(); host.Resize(w, h); });

await host.StartAsync(initW, initH, CONTENT_BASE, MANIFEST_PATH, START_SCENE);

let last = performance.now();
function frame(now) {
    host.Frame((now - last) / 1000);
    last = now;
    requestAnimationFrame(frame);
}
requestAnimationFrame(frame);
""".Replace("__START_SCENE__", startScene);
}
