namespace Spot.Build;

/// <summary>
/// The static <c>wwwroot</c> assets for a browser build: the host page and the JavaScript that bridges the
/// engine's <c>[JSImport]</c>/<c>[JSExport]</c> surface to the DOM. <c>main.js</c> owns the canvas' WebGL2
/// context and implements the <c>spot-gl</c> (graphics) and <c>spot-host</c> (fetch) module imports that
/// <see cref="Spot.Rendering.IGraphicsDevice"/>'s WebGL2 backend and the browser host call into, then drives
/// the frame loop through <c>requestAnimationFrame</c> and forwards DOM input events.
/// </summary>
internal static class BrowserTemplate
{
    /// <summary>Builds the host page for a browser build with the given window title.</summary>
    public static string IndexHtml(string title) => """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>__TITLE__</title>
    <style>
        html, body { margin: 0; height: 100%; background: #0b0b12; overflow: hidden; }
        #canvas { display: block; width: 100vw; height: 100vh; touch-action: none; }
        #loading {
            position: fixed; inset: 0; display: flex; flex-direction: column;
            align-items: center; justify-content: center; background: #0b0b12;
            color: #8888aa; font-family: system-ui, sans-serif; font-size: 14px; gap: 16px;
            pointer-events: none;
        }
        #loading-bar-bg {
            width: 220px; height: 3px; background: #1e1e2e; border-radius: 2px; overflow: hidden;
        }
        #loading-bar { height: 100%; width: 0%; background: #6464aa; border-radius: 2px;
            transition: width 0.2s ease;
        }
    </style>
</head>
<body>
    <canvas id="canvas" tabindex="0"></canvas>
    <div id="loading">
        <span id="loading-text">Loading…</span>
        <div id="loading-bar-bg"><div id="loading-bar"></div></div>
    </div>
    <script type="module" src="./main.js"></script>
</body>
</html>
""".Replace("__TITLE__", title);

    /// <summary>
    /// Builds <c>main.js</c> for a browser build. The cooked content is served under <c>content/</c> with a
    /// <c>content-index.txt</c> manifest of files to preload; <paramref name="startScene"/> is the cooked start
    /// scene reference passed to the engine host.
    /// </summary>
    public static string MainJs(string startScene) => """
// Generated by Spot.Build. Bridges the DOM + WebGL2 to the Spot engine's browser host.
import { dotnet } from './_framework/dotnet.js';

const ENGINE_ASSEMBLY = 'Spot.Engine';
const CONTENT_BASE = 'content';
const MANIFEST_PATH = 'manifest.json';
const START_SCENE = '__START_SCENE__';

const canvas = document.getElementById('canvas');

function sizeCanvas() {
    const dpr = window.devicePixelRatio || 1;
    canvas.width = Math.max(1, Math.floor(canvas.clientWidth * dpr));
    canvas.height = Math.max(1, Math.floor(canvas.clientHeight * dpr));
    return [canvas.width, canvas.height];
}

const [initW, initH] = sizeCanvas();

const gl = canvas.getContext('webgl2', { antialias: true, alpha: false });
if (!gl) {
    document.body.insertAdjacentHTML('beforeend', '<p style="color:red">WebGL2 is not available in this browser.</p>');
    throw new Error('WebGL2 not supported');
}

// Makes RGBA16F color attachments renderable (HDR render targets). Depth textures are core in WebGL2.
gl.getExtension('EXT_color_buffer_float');

// JS-side handle table: C# refers to GL objects (buffers, shaders, programs, textures, uniform locations)
// by integer index. Index 0 is reserved as the null handle.
const objs = [null];
const reg = (o) => { objs.push(o); return objs.length - 1; };

const glImports = {
    viewport: (x, y, w, h) => gl.viewport(x, y, w, h),
    scissor: (x, y, w, h) => gl.scissor(x, y, w, h),
    clearColor: (r, g, b, a) => gl.clearColor(r, g, b, a),
    clear: (mask) => gl.clear(mask),
    enable: (cap) => gl.enable(cap),
    disable: (cap) => gl.disable(cap),
    depthMask: (flag) => gl.depthMask(flag),
    blendFunc: (s, d) => gl.blendFunc(s, d),
    drawArrays: (mode, first, count) => gl.drawArrays(mode, first, count),
    drawElements: (mode, count, type, offset) => gl.drawElements(mode, count, type, offset),

    createBuffer: () => reg(gl.createBuffer()),
    bindBuffer: (target, b) => gl.bindBuffer(target, objs[b]),
    bufferData: (target, data, usage) => gl.bufferData(target, data.slice(), usage),
    bufferDataSize: (target, size, usage) => gl.bufferData(target, size, usage),
    bufferSubData: (target, offset, data) => gl.bufferSubData(target, offset, data.slice()),
    deleteBuffer: (b) => gl.deleteBuffer(objs[b]),

    createVertexArray: () => reg(gl.createVertexArray()),
    bindVertexArray: (v) => gl.bindVertexArray(objs[v]),
    enableVertexAttribArray: (i) => gl.enableVertexAttribArray(i),
    vertexAttribPointer: (i, size, type, norm, stride, offset) =>
        gl.vertexAttribPointer(i, size, type, norm, stride, offset),
    deleteVertexArray: (v) => gl.deleteVertexArray(objs[v]),

    createShader: (type) => reg(gl.createShader(type)),
    shaderSource: (s, src) => gl.shaderSource(objs[s], src),
    compileShader: (s) => gl.compileShader(objs[s]),
    getShaderCompileStatus: (s) => gl.getShaderParameter(objs[s], gl.COMPILE_STATUS),
    getShaderInfoLog: (s) => gl.getShaderInfoLog(objs[s]) ?? '',
    deleteShader: (s) => gl.deleteShader(objs[s]),

    createProgram: () => reg(gl.createProgram()),
    attachShader: (p, s) => gl.attachShader(objs[p], objs[s]),
    detachShader: (p, s) => gl.detachShader(objs[p], objs[s]),
    linkProgram: (p) => gl.linkProgram(objs[p]),
    getProgramLinkStatus: (p) => gl.getProgramParameter(objs[p], gl.LINK_STATUS),
    getProgramInfoLog: (p) => gl.getProgramInfoLog(objs[p]) ?? '',
    deleteProgram: (p) => gl.deleteProgram(objs[p]),
    useProgram: (p) => gl.useProgram(objs[p]),

    getUniformLocation: (p, name) => { const l = gl.getUniformLocation(objs[p], name); return l ? reg(l) : -1; },
    uniform1i: (loc, v) => { if (loc >= 0) gl.uniform1i(objs[loc], v); },
    uniform1f: (loc, v) => { if (loc >= 0) gl.uniform1f(objs[loc], v); },
    uniform2f: (loc, x, y) => { if (loc >= 0) gl.uniform2f(objs[loc], x, y); },
    uniform3f: (loc, x, y, z) => { if (loc >= 0) gl.uniform3f(objs[loc], x, y, z); },
    uniform4f: (loc, x, y, z, w) => { if (loc >= 0) gl.uniform4f(objs[loc], x, y, z, w); },
    uniformMatrix4fv: (loc, data) => { if (loc >= 0) gl.uniformMatrix4fv(objs[loc], false, new Float32Array(data.slice().buffer)); },

    createTexture: () => reg(gl.createTexture()),
    bindTexture: (unit, tex) => { gl.activeTexture(gl.TEXTURE0 + unit); gl.bindTexture(gl.TEXTURE_2D, objs[tex]); },
    texParameteri: (name, value) => gl.texParameteri(gl.TEXTURE_2D, name, value),
    texImage2DRgba8: (w, h, data) =>
        gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA8, w, h, 0, gl.RGBA, gl.UNSIGNED_BYTE, data.slice()),
    // Render-target / typed texture allocation. `format` is a small code (not a GL enum): 0 RGBA8, 1 RGBA16F,
    // 2 depth32f, 3 depth24-stencil8. A zero-length view means "allocate uninitialized" (an FBO attachment).
    texImage2D: (format, w, h, data) => {
        const spec = [
            [gl.RGBA8, gl.RGBA, gl.UNSIGNED_BYTE],
            [gl.RGBA16F, gl.RGBA, gl.FLOAT],
            [gl.DEPTH_COMPONENT32F, gl.DEPTH_COMPONENT, gl.FLOAT],
            [gl.DEPTH24_STENCIL8, gl.DEPTH_STENCIL, gl.UNSIGNED_INT_24_8],
        ][format];
        const pixels = (data && data.length) ? data.slice() : null;
        gl.texImage2D(gl.TEXTURE_2D, 0, spec[0], w, h, 0, spec[1], spec[2], pixels);
    },
    texCompareMode: (enabled) => {
        gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_COMPARE_MODE, enabled ? gl.COMPARE_REF_TO_TEXTURE : gl.NONE);
        if (enabled) gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_COMPARE_FUNC, gl.LEQUAL);
    },
    generateMipmap2D: () => gl.generateMipmap(gl.TEXTURE_2D),
    deleteTexture: (t) => gl.deleteTexture(objs[t]),

    createFramebuffer: () => reg(gl.createFramebuffer()),
    // Handle 0 is the default framebuffer (the canvas): bind null.
    bindFramebuffer: (fb) => gl.bindFramebuffer(gl.FRAMEBUFFER, fb === 0 ? null : objs[fb]),
    framebufferTexture2D: (attachment, tex) => {
        const point = [gl.COLOR_ATTACHMENT0, gl.DEPTH_ATTACHMENT, gl.DEPTH_STENCIL_ATTACHMENT][attachment];
        gl.framebufferTexture2D(gl.FRAMEBUFFER, point, gl.TEXTURE_2D, objs[tex], 0);
    },
    checkFramebufferComplete: () => gl.checkFramebufferStatus(gl.FRAMEBUFFER) === gl.FRAMEBUFFER_COMPLETE,
    setColorBuffersNone: () => { gl.drawBuffers([gl.NONE]); gl.readBuffer(gl.NONE); },
    blitDepth: (src, dst, w, h, dx, dy, dw, dh) => {
        gl.bindFramebuffer(gl.READ_FRAMEBUFFER, src === 0 ? null : objs[src]);
        gl.bindFramebuffer(gl.DRAW_FRAMEBUFFER, dst === 0 ? null : objs[dst]);
        gl.blitFramebuffer(0, 0, w, h, dx, dy, dx + dw, dy + dh, gl.DEPTH_BUFFER_BIT, gl.NEAREST);
        gl.bindFramebuffer(gl.FRAMEBUFFER, dst === 0 ? null : objs[dst]);
    },
    deleteFramebuffer: (fb) => gl.deleteFramebuffer(objs[fb]),
};

const hostImports = {
    fetchText: async (url) => {
        const r = await fetch(url);
        if (!r.ok) throw new Error(`fetch ${url}: ${r.status}`);
        return await r.text();
    },
    fetchBase64: async (url) => {
        const r = await fetch(url);
        if (!r.ok) throw new Error(`fetch ${url}: ${r.status}`);
        const bytes = new Uint8Array(await r.arrayBuffer());
        let binary = '';
        const chunk = 0x8000;
        for (let i = 0; i < bytes.length; i += chunk) {
            binary += String.fromCharCode.apply(null, bytes.subarray(i, i + chunk));
        }
        return btoa(binary);
    },
};

// ---- Web Audio (spot-audio module) ----
// One AudioContext drives the mixer. C# refers to buffers and voices by integer handle (index 0 = null),
// mirroring the GL handle table. OpenAL sources are persistent; a Web Audio AudioBufferSourceNode is one-shot,
// so each voice keeps a persistent GainNode/PannerNode and recreates the source node on every play, tracking
// its own state (0 initial / 1 playing / 2 paused / 3 stopped) for the mixer's free-source polling.
let audioCtx = null;
let masterGain = null;
const audioBuffers = [null];
const audioSources = [null];

// (Re)connects a voice's gain to the graph: spatial routes through its panner, non-spatial straight to master.
function audioRoute(v) {
    try { v.gain.disconnect(); } catch (e) {}
    try { v.panner.disconnect(); } catch (e) {}
    if (v.spatial) { v.gain.connect(v.panner); v.panner.connect(masterGain); }
    else { v.gain.connect(masterGain); }
}

function audioStopNode(v) {
    if (v.node) { try { v.node.onended = null; v.node.stop(); } catch (e) {} v.node = null; }
}

const audioImports = {
    open: () => {
        try {
            const AC = window.AudioContext || window.webkitAudioContext;
            if (!AC) return false;
            audioCtx = new AC();
            masterGain = audioCtx.createGain();
            masterGain.connect(audioCtx.destination);
            // Autoplay policy: the context starts suspended until a user gesture. Resume on the first
            // pointer/key press, then drop the one-shot unlock listeners.
            const unlock = () => {
                if (audioCtx && audioCtx.state === 'suspended') audioCtx.resume();
                window.removeEventListener('pointerdown', unlock);
                window.removeEventListener('keydown', unlock);
            };
            window.addEventListener('pointerdown', unlock);
            window.addEventListener('keydown', unlock);
            return true;
        } catch (e) {
            console.error('Web Audio init failed', e);
            return false;
        }
    },
    close: () => { if (audioCtx) { audioCtx.close(); audioCtx = null; masterGain = null; } },

    genSource: () => {
        const panner = audioCtx.createPanner();
        panner.distanceModel = 'linear';
        const v = { gain: audioCtx.createGain(), panner, node: null, buffer: 0, pitch: 1, loop: false,
                    spatial: false, state: 0, startTime: 0, offset: 0 };
        audioSources.push(v);
        audioRoute(v);
        return audioSources.length - 1;
    },
    deleteSource: (s) => {
        const v = audioSources[s]; if (!v) return;
        audioStopNode(v);
        try { v.gain.disconnect(); } catch (e) {}
        try { v.panner.disconnect(); } catch (e) {}
        audioSources[s] = null;
    },
    playSource: (s) => {
        const v = audioSources[s]; if (!v || !v.buffer) return;
        const buf = audioBuffers[v.buffer]; if (!buf) return;
        audioStopNode(v);
        const node = audioCtx.createBufferSource();
        node.buffer = buf;
        node.playbackRate.value = v.pitch;
        node.loop = v.loop;
        node.connect(v.gain);
        const startOffset = (v.state === 2) ? v.offset : 0; // resume from the paused offset, else from the start
        node.onended = () => { if (v.node === node) { v.node = null; v.state = 3; v.offset = 0; } };
        try { node.start(0, startOffset); } catch (e) { return; }
        v.node = node;
        v.startTime = audioCtx.currentTime - startOffset / Math.max(0.01, v.pitch);
        v.state = 1;
    },
    stopSource: (s) => { const v = audioSources[s]; if (!v) return; audioStopNode(v); v.offset = 0; v.state = 3; },
    pauseSource: (s) => {
        const v = audioSources[s]; if (!v || v.state !== 1) return;
        const dur = (v.node && v.node.buffer) ? v.node.buffer.duration : 0;
        const elapsed = (audioCtx.currentTime - v.startTime) * v.pitch;
        v.offset = (v.loop && dur > 0) ? (elapsed % dur) : Math.min(elapsed, dur);
        audioStopNode(v);
        v.state = 2;
    },
    getSourceState: (s) => { const v = audioSources[s]; return v ? v.state : 0; },
    setSourceBuffer: (s, b) => { const v = audioSources[s]; if (v) v.buffer = b; },
    getSourceBuffer: (s) => { const v = audioSources[s]; return v ? v.buffer : 0; },
    setSourceGain: (s, g) => { const v = audioSources[s]; if (v) v.gain.gain.value = g; },
    setSourcePitch: (s, p) => { const v = audioSources[s]; if (v) { v.pitch = p; if (v.node) v.node.playbackRate.value = p; } },
    setSourceLooping: (s, l) => { const v = audioSources[s]; if (v) { v.loop = l; if (v.node) v.node.loop = l; } },
    setSourceRelative: (s, rel) => { const v = audioSources[s]; if (!v) return; v.spatial = !rel; audioRoute(v); },
    setSourcePosition: (s, x, y, z) => {
        const v = audioSources[s]; if (!v) return;
        const p = v.panner;
        if (p.positionX) { p.positionX.value = x; p.positionY.value = y; p.positionZ.value = z; }
        else p.setPosition(x, y, z);
    },
    setSourceReferenceDistance: (s, d) => { const v = audioSources[s]; if (v) v.panner.refDistance = d; },
    setSourceMaxDistance: (s, d) => { const v = audioSources[s]; if (v) v.panner.maxDistance = Math.max(d, v.panner.refDistance + 0.01); },

    genBuffer: () => { audioBuffers.push(null); return audioBuffers.length - 1; },
    deleteBuffer: (b) => { audioBuffers[b] = null; },
    uploadBuffer: (b, channels, sampleRate, data) => {
        const pcm = new Int16Array(data.slice().buffer);
        const frames = Math.floor(pcm.length / channels);
        const buf = audioCtx.createBuffer(channels, Math.max(1, frames), sampleRate);
        for (let ch = 0; ch < channels; ch++) {
            const out = buf.getChannelData(ch);
            for (let i = 0; i < frames; i++) out[i] = pcm[i * channels + ch] / 32768;
        }
        audioBuffers[b] = buf;
    },
    setListenerGain: (g) => { if (masterGain) masterGain.gain.value = g; },
    setListenerPosition: (x, y, z) => {
        const l = audioCtx.listener;
        if (l.positionX) { l.positionX.value = x; l.positionY.value = y; l.positionZ.value = z; }
        else l.setPosition(x, y, z);
    },
    setListenerOrientation: (fx, fy, fz, ux, uy, uz) => {
        const l = audioCtx.listener;
        if (l.forwardX) {
            l.forwardX.value = fx; l.forwardY.value = fy; l.forwardZ.value = fz;
            l.upX.value = ux; l.upY.value = uy; l.upZ.value = uz;
        } else {
            l.setOrientation(fx, fy, fz, ux, uy, uz);
        }
    },
};

const loading = document.getElementById('loading');
const loadingText = document.getElementById('loading-text');
const loadingBar = document.getElementById('loading-bar');
function setProgress(text, pct) {
    if (loadingText) loadingText.textContent = text;
    if (loadingBar) loadingBar.style.width = `${Math.round(pct * 100)}%`;
}

setProgress('Initializing runtime…', 0.1);
const { setModuleImports, getAssemblyExports, getConfig, runMain } = await dotnet.create();
// ---- Pointer lock / cursor (spot-input module) ----
// The engine drives Input.CursorLocked through this. Locking uses the Pointer Lock API (hides the cursor and
// switches pointermove to relative movementX/Y). Browsers only grant the lock from a user gesture, so a
// request made outside one is retried on the next canvas click (pointerdown wiring below).
let cursorLockDesired = false;
function requestLock() {
    if (document.pointerLockElement !== canvas && canvas.requestPointerLock) {
        const p = canvas.requestPointerLock();
        if (p && typeof p.catch === 'function') p.catch(() => {});
    }
}
const inputImports = {
    setCursorLocked: (locked) => {
        cursorLockDesired = locked;
        if (locked) requestLock();
        else if (document.pointerLockElement === canvas && document.exitPointerLock) document.exitPointerLock();
    },
    isCursorLocked: () => document.pointerLockElement === canvas,
};

setModuleImports('spot-gl', { gl: glImports });
setModuleImports('spot-host', { host: hostImports });
setModuleImports('spot-audio', { audio: audioImports });
setModuleImports('spot-input', { input: inputImports });

getConfig();
const exports = await getAssemblyExports(ENGINE_ASSEMBLY);
const host = exports.Spot.Browser.BrowserHost;

setProgress('Loading runtime…', 0.3);
await runMain();

// Wire input before StartAsync so presses during the content load are captured. StartAsync's synchronous
// prefix installs the renderer before its first await, so a Resize firing mid-load is safe; key/pointer
// events just queue and are drained once the frame loop begins.
window.addEventListener('keydown', (e) => { host.KeyDown(e.code); if (e.key.length === 1) host.TextInput(e.key); e.preventDefault(); });
window.addEventListener('keyup', (e) => { host.KeyUp(e.code); e.preventDefault(); });
canvas.addEventListener('pointermove', (e) => {
    const dpr = window.devicePixelRatio || 1;
    // While locked the browser freezes offsetX/Y and reports motion via movementX/Y; feed that as relative.
    if (document.pointerLockElement === canvas) host.PointerMoveRelative(e.movementX * dpr, e.movementY * dpr);
    else host.PointerMove(e.offsetX * dpr, e.offsetY * dpr);
});
canvas.addEventListener('pointerdown', (e) => {
    canvas.focus();
    // Engage a deferred lock request now that we're in a user gesture (the engine asked for it earlier).
    if (cursorLockDesired && document.pointerLockElement !== canvas) requestLock();
    host.PointerDown(e.button);
});
window.addEventListener('pointerup', (e) => host.PointerUp(e.button));
canvas.addEventListener('wheel', (e) => { host.Wheel(e.deltaX, e.deltaY); e.preventDefault(); }, { passive: false });
canvas.addEventListener('contextmenu', (e) => e.preventDefault());
window.addEventListener('resize', () => { const [w, h] = sizeCanvas(); host.Resize(w, h); });

setProgress('Loading content…', 0.5);
await host.StartAsync(initW, initH, CONTENT_BASE, MANIFEST_PATH, START_SCENE);

if (loading) loading.style.display = 'none';
canvas.focus();

let last = performance.now();
function frame(now) {
    host.Frame((now - last) / 1000);
    last = now;
    requestAnimationFrame(frame);
}
requestAnimationFrame(frame);
""".Replace("__START_SCENE__", startScene);
}
